#!/bin/bash

if [ $# -lt 2 ]; then
	echo "Usage: $0 <elf file name> <rom|dram> [output file base name]"
	exit 1
fi

MODE=$2
ELF=$1

if [ $# -eq 3 ]; then
	OUT_BASE_NAME=$3
else
	OUT_BASE_NAME=${ELF%.*}
fi

#echo output: "$OUT_BASE_NAME"


brew-none-elf-objcopy --strip-all --output-target binary $ELF $OUT_BASE_NAME.bin || exit 1
hexdump -e '/1 "%02x" "\n"' -v $OUT_BASE_NAME.bin > $OUT_BASE_NAME.mef || exit 1

if [ "$MODE" == "rom" ]; then
	exit 0
fi

if [ "$MODE" == "dram" ]; then
	sed -ne "w $OUT_BASE_NAME.0.mef" -e "n;" $OUT_BASE_NAME.mef || exit 1
	sed -ne "" -e "n; w $OUT_BASE_NAME.1.mef" $OUT_BASE_NAME.mef || exit 1
	exit 0
fi

echo "Invalid mode: $MODE"
exit 1
